from alembic import op
import sqlalchemy as sa
revision = "0008"
down_revision = "0007"
branch_labels = None
depends_on = None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=True),
    sa.Column('document_hash', sa.String(length=64), nullable=True),
    sa.Column('criteria_version', sa.Integer(), nullable=False),
    sa.Column('execution_id', sa.String(length=36), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('method', sa.String(length=100), nullable=False),
    sa.Column('policy_version', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('profile_json', sa.Text(), nullable=False),
    sa.Column('sources_json', sa.Text(), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['execution_id'], ['ai_executions.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['analysis_runs.id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('execution_id')
    )
    op.create_index(op.f('ix_analysis_runs_application_id'), 'analysis_runs', ['application_id'], unique=False)
    op.create_table('analysis_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('content_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    # Preserve the previously available result without inventing a CV identity.
    connection = op.get_bind()
    metadata = sa.MetaData()
    runs = sa.Table("analysis_runs", metadata, autoload_with=connection)
    for match in connection.execute(sa.text("SELECT * FROM candidate_matches")).mappings():
        connection.execute(runs.insert().values(application_id=match["application_id"],
            resume_id=match["resume_id"], criteria_version=match["criteria_version"],
            method="legacy-keywords", policy_version="legacy-unversioned", status="legacy-unverified",
            score=match["overall_score"], profile_json="{}", sources_json="[]",
            result_json=match["breakdown_json"], reason="Resultado antigo preservado; requer nova análise localizada."))

def downgrade():
    raise RuntimeError("Restore backup to preserve history")
